### ISSUE TITLE
Presets should be read from collections

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#691] opened 2024-06-18 13:59 UTC
The data here: https://github.com/ForkbombEu/signroom/blob/a97d291e6c4fdc5668e12ec65b90b1b1edc09dc3/webapp/src/routes/%5B%5Blang%5D%5D/my/organizations/%5Bid%5D/templates/_partials/templatePresets.ts#L12-L40

Should be read by a collection: we need to update presets continously, without the need to redeploy. The collection should only be writable in the admin panel.

**Comment by puria** [comment] 2024-06-18 15:52
Bravissimo duplicate of https://github.com/ForkbombEu/signroom/issues/680

**Closed** 2024-09-20 10:48 UTC
